# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: minionn-onnx.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import onnx as onnx__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='minionn-onnx.proto',
  package='minionn',
  syntax='proto3',
  serialized_pb=_b('\n\x12minionn-onnx.proto\x12\x07minionn\x1a\nonnx.proto\"A\n\x15PrecomputationRequest\x12\x15\n\rrequest_model\x18\x01 \x01(\x08\x12\x11\n\trequest_w\x18\x02 \x01(\x08\"D\n\x16PrecomputationResponse\x12\x1f\n\x05model\x18\x01 \x01(\x0b\x32\x10.onnx.ModelProto\x12\t\n\x01w\x18\x02 \x03(\x0c\"+\n\x12\x43omputationRequest\x12\t\n\x01u\x18\x01 \x03(\x0c\x12\n\n\x02xs\x18\x02 \x03(\x03\"!\n\x13\x43omputationResponse\x12\n\n\x02ys\x18\x01 \x03(\x03\x32\xaa\x01\n\x07MinioNN\x12S\n\x0ePrecomputation\x12\x1e.minionn.PrecomputationRequest\x1a\x1f.minionn.PrecomputationResponse\"\x00\x12J\n\x0b\x43omputation\x12\x1b.minionn.ComputationRequest\x1a\x1c.minionn.ComputationResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[onnx__pb2.DESCRIPTOR,])




_PRECOMPUTATIONREQUEST = _descriptor.Descriptor(
  name='PrecomputationRequest',
  full_name='minionn.PrecomputationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_model', full_name='minionn.PrecomputationRequest.request_model', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_w', full_name='minionn.PrecomputationRequest.request_w', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=108,
)


_PRECOMPUTATIONRESPONSE = _descriptor.Descriptor(
  name='PrecomputationResponse',
  full_name='minionn.PrecomputationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model', full_name='minionn.PrecomputationResponse.model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='w', full_name='minionn.PrecomputationResponse.w', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=178,
)


_COMPUTATIONREQUEST = _descriptor.Descriptor(
  name='ComputationRequest',
  full_name='minionn.ComputationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='u', full_name='minionn.ComputationRequest.u', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='xs', full_name='minionn.ComputationRequest.xs', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=223,
)


_COMPUTATIONRESPONSE = _descriptor.Descriptor(
  name='ComputationResponse',
  full_name='minionn.ComputationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ys', full_name='minionn.ComputationResponse.ys', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=258,
)

_PRECOMPUTATIONRESPONSE.fields_by_name['model'].message_type = onnx__pb2.ModelProto
DESCRIPTOR.message_types_by_name['PrecomputationRequest'] = _PRECOMPUTATIONREQUEST
DESCRIPTOR.message_types_by_name['PrecomputationResponse'] = _PRECOMPUTATIONRESPONSE
DESCRIPTOR.message_types_by_name['ComputationRequest'] = _COMPUTATIONREQUEST
DESCRIPTOR.message_types_by_name['ComputationResponse'] = _COMPUTATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PrecomputationRequest = _reflection.GeneratedProtocolMessageType('PrecomputationRequest', (_message.Message,), dict(
  DESCRIPTOR = _PRECOMPUTATIONREQUEST,
  __module__ = 'minionn_onnx_pb2'
  # @@protoc_insertion_point(class_scope:minionn.PrecomputationRequest)
  ))
_sym_db.RegisterMessage(PrecomputationRequest)

PrecomputationResponse = _reflection.GeneratedProtocolMessageType('PrecomputationResponse', (_message.Message,), dict(
  DESCRIPTOR = _PRECOMPUTATIONRESPONSE,
  __module__ = 'minionn_onnx_pb2'
  # @@protoc_insertion_point(class_scope:minionn.PrecomputationResponse)
  ))
_sym_db.RegisterMessage(PrecomputationResponse)

ComputationRequest = _reflection.GeneratedProtocolMessageType('ComputationRequest', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTATIONREQUEST,
  __module__ = 'minionn_onnx_pb2'
  # @@protoc_insertion_point(class_scope:minionn.ComputationRequest)
  ))
_sym_db.RegisterMessage(ComputationRequest)

ComputationResponse = _reflection.GeneratedProtocolMessageType('ComputationResponse', (_message.Message,), dict(
  DESCRIPTOR = _COMPUTATIONRESPONSE,
  __module__ = 'minionn_onnx_pb2'
  # @@protoc_insertion_point(class_scope:minionn.ComputationResponse)
  ))
_sym_db.RegisterMessage(ComputationResponse)



_MINIONN = _descriptor.ServiceDescriptor(
  name='MinioNN',
  full_name='minionn.MinioNN',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=261,
  serialized_end=431,
  methods=[
  _descriptor.MethodDescriptor(
    name='Precomputation',
    full_name='minionn.MinioNN.Precomputation',
    index=0,
    containing_service=None,
    input_type=_PRECOMPUTATIONREQUEST,
    output_type=_PRECOMPUTATIONRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Computation',
    full_name='minionn.MinioNN.Computation',
    index=1,
    containing_service=None,
    input_type=_COMPUTATIONREQUEST,
    output_type=_COMPUTATIONRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MINIONN)

DESCRIPTOR.services_by_name['MinioNN'] = _MINIONN

# @@protoc_insertion_point(module_scope)
